name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan


    - name: Terraform Apply
      if: github.event_name != 'pull_request'
      run: terraform apply -auto-approve tfplan

    - name: Terraform Output
      run: terraform output

  
    - name: Deploy Completed
      run: |
        echo "Deployment completed."
        echo "VNet ID: ${{ env.VNET_ID }}"
