name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0

    - name: Configure Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    - name: Comment on Pull Request (if available)
      if: github.event_name == 'pull_request'
      run: |
        echo "::set-output name=plan_file::tfplan"
        echo "##[set-output name=plan_file]tfplan"

    - name: Terraform Apply
      if: github.event_name != 'pull_request'
      run: terraform apply -auto-approve tfplan

    - name: Terraform Output
      run: terraform output

    - name: Set Outputs as Environment Variables
      id: set_outputs
      run: echo "::set-env name=VNET_ID::$(terraform output -raw vnet_id)"

    - name: Deploy Completed
      run: |
        echo "Deployment completed."
        echo "VNet ID: ${{ env.VNET_ID }}"
